apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secrets-sops
spec:
    secretTemplates:
        - name: postgre-secret
          stringData:
            password: My$ecrETPAss0rd*
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19tfqxgdgx3fe96j8fyy0c65nsfj8ku8sl4ccfxnzpn3xpakylg5s8sgac7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmajZhUWN4MVRja1ZDQ0pv
            d2pVMVNleTZld0c3TkR0dUNYMnhiWnJFQW44CnRRUjlhUnpJOXNJK002a0RSQmpT
            TWNwMW1OS1QxQTdTVmJGT2psT3QyZ0UKLS0tIExvUlRteTNNZjEyaW8zYmRjUFp6
            azFnS0tqNGdGYWk4TTMweHJmUVlrSG8KjTLSFroHOYtUEo0S8F4yrvs1zc6MqSac
            Qu3FunCnWT2iHtofWV4fz8eEXTxHWKRzAS1uBxkztCvxVM6atfr2vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T10:09:32Z"
    mac: ENC[AES256_GCM,data:J2sadTVTlzzHZbNfIYHDbLx4U0qDJy4ZXEQZn01bicG6ODmIiceMV9zY2dyBoFp1FwdRxK6NNVbn73IYL3FlAEL1472kyAJSFbg5hY+AOQpsZ+kyeqb5zRi4hhrVARPqZKMIbc/HRv/UiGJYasA+zDOuO+G2uC69lahxEx9JXt4=,iv:7W6g2BvQTgl44zDRVJUudHRhg77JL+mpnTRgh5fPAV0=,tag:8VEZvpJE0XoxAahe88/QZQ==,type:str]
    pgp: []
    encrypted_suffix: token
    version: 3.8.1
